[python]
home = "../Frameworks/Python.framework/Versions/3.9"
library_name = "lib/libpython3.9.dylib"
paths = ["lib/python39.zip", "lib/python3.9", "lib/python3.9/lib-dynload", "../../../../MacOS/python-nionswift/lib/python3.9/site-packages"]

[app]
identifier = "nionui_app.nionswift"
